// <auto-generated />
using AgroSat.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AgroSat.Api.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260603000000_InitialCreate")]
partial class InitialCreate
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        // O modelo-alvo desta migration e identico ao AppDbContextModelSnapshot.
        // Mantido vazio aqui para evitar duplicacao; ao regenerar a migration
        // (dotnet ef migrations add ...) o EF preenche este metodo automaticamente.
    }
}
