// <auto-generated />
// EXEMPLO/PONTO DE PARTIDA escrito junto com a migration InitialCreate.
// Se o Kaiky regenerar a migration (recomendado), o EF reescreve este arquivo.
using System;
using AgroSat.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgroSat.Api.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

        foreach (var seq in new[]
        {
            "SEQ_USUARIO", "SEQ_CULTURA", "SEQ_PROPRIEDADE", "SEQ_TALHAO", "SEQ_SENSOR",
            "SEQ_LEITURA", "SEQ_DADO_SAT", "SEQ_ALERTA", "SEQ_RECOMENDACAO", "SEQ_IRRIGACAO"
        })
        {
            modelBuilder.HasSequence<long>(seq);
        }

        modelBuilder.Entity("AgroSat.Api.Models.Usuario", b =>
        {
            b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("NUMBER(19)")
                .HasColumnName("ID_USUARIO").HasDefaultValueSql("SEQ_USUARIO.NEXTVAL");
            b.Property<string>("Nome").IsRequired().HasMaxLength(120).HasColumnType("NVARCHAR2(120)").HasColumnName("NOME");
            b.Property<string>("Cpf").IsRequired().HasMaxLength(11).HasColumnType("NVARCHAR2(11)").HasColumnName("CPF");
            b.Property<string>("Email").IsRequired().HasMaxLength(120).HasColumnType("NVARCHAR2(120)").HasColumnName("EMAIL");
            b.Property<string>("Senha").IsRequired().HasMaxLength(255).HasColumnType("NVARCHAR2(255)").HasColumnName("SENHA");
            b.Property<string>("Telefone").HasMaxLength(20).HasColumnType("NVARCHAR2(20)").HasColumnName("TELEFONE");
            b.Property<DateTime?>("DataCadastro").HasColumnType("TIMESTAMP(7)").HasColumnName("DATA_CADASTRO");
            b.HasKey("Id");
            b.HasIndex("Cpf").IsUnique();
            b.HasIndex("Email").IsUnique();
            b.ToTable("USUARIO");
        });

        modelBuilder.Entity("AgroSat.Api.Models.Cultura", b =>
        {
            b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("NUMBER(19)")
                .HasColumnName("ID_CULTURA").HasDefaultValueSql("SEQ_CULTURA.NEXTVAL");
            b.Property<string>("Nome").IsRequired().HasMaxLength(80).HasColumnType("NVARCHAR2(80)").HasColumnName("NOME");
            b.Property<decimal?>("UmidadeIdealMin").HasColumnType("NUMBER(5,2)").HasColumnName("UMIDADE_IDEAL_MIN");
            b.Property<decimal?>("UmidadeIdealMax").HasColumnType("NUMBER(5,2)").HasColumnName("UMIDADE_IDEAL_MAX");
            b.Property<decimal?>("TempIdealMin").HasColumnType("NUMBER(5,2)").HasColumnName("TEMP_IDEAL_MIN");
            b.Property<decimal?>("TempIdealMax").HasColumnType("NUMBER(5,2)").HasColumnName("TEMP_IDEAL_MAX");
            b.Property<int?>("CicloDias").HasColumnType("NUMBER(10)").HasColumnName("CICLO_DIAS");
            b.HasKey("Id");
            b.ToTable("CULTURA");
        });

        modelBuilder.Entity("AgroSat.Api.Models.Propriedade", b =>
        {
            b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("NUMBER(19)")
                .HasColumnName("ID_PROPRIEDADE").HasDefaultValueSql("SEQ_PROPRIEDADE.NEXTVAL");
            b.Property<string>("Nome").IsRequired().HasMaxLength(120).HasColumnType("NVARCHAR2(120)").HasColumnName("NOME");
            b.Property<decimal?>("Latitude").HasColumnType("NUMBER(9,6)").HasColumnName("LATITUDE");
            b.Property<decimal?>("Longitude").HasColumnType("NUMBER(9,6)").HasColumnName("LONGITUDE");
            b.Property<decimal?>("AreaTotalHa").HasColumnType("NUMBER(10,2)").HasColumnName("AREA_TOTAL_HA");
            b.Property<string>("Municipio").HasMaxLength(80).HasColumnType("NVARCHAR2(80)").HasColumnName("MUNICIPIO");
            b.Property<string>("Uf").HasMaxLength(2).HasColumnType("NVARCHAR2(2)").HasColumnName("UF");
            b.Property<long>("IdUsuario").HasColumnType("NUMBER(19)").HasColumnName("ID_USUARIO");
            b.HasKey("Id");
            b.HasIndex("IdUsuario");
            b.ToTable("PROPRIEDADE");
        });

        modelBuilder.Entity("AgroSat.Api.Models.Talhao", b =>
        {
            b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("NUMBER(19)")
                .HasColumnName("ID_TALHAO").HasDefaultValueSql("SEQ_TALHAO.NEXTVAL");
            b.Property<string>("Nome").IsRequired().HasMaxLength(80).HasColumnType("NVARCHAR2(80)").HasColumnName("NOME");
            b.Property<decimal?>("AreaHa").HasColumnType("NUMBER(10,2)").HasColumnName("AREA_HA");
            b.Property<long>("IdPropriedade").HasColumnType("NUMBER(19)").HasColumnName("ID_PROPRIEDADE");
            b.Property<long?>("IdCultura").HasColumnType("NUMBER(19)").HasColumnName("ID_CULTURA");
            b.HasKey("Id");
            b.HasIndex("IdPropriedade");
            b.HasIndex("IdCultura");
            b.ToTable("TALHAO");
        });

        modelBuilder.Entity("AgroSat.Api.Models.Sensor", b =>
        {
            b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("NUMBER(19)")
                .HasColumnName("ID_SENSOR").HasDefaultValueSql("SEQ_SENSOR.NEXTVAL");
            b.Property<string>("Codigo").IsRequired().HasMaxLength(40).HasColumnType("NVARCHAR2(40)").HasColumnName("CODIGO");
            b.Property<string>("Tipo").HasMaxLength(40).HasColumnType("NVARCHAR2(40)").HasColumnName("TIPO");
            b.Property<string>("Status").HasMaxLength(20).HasColumnType("NVARCHAR2(20)").HasColumnName("STATUS");
            b.Property<DateTime?>("DataInstalacao").HasColumnType("TIMESTAMP(7)").HasColumnName("DATA_INSTALACAO");
            b.Property<long>("IdTalhao").HasColumnType("NUMBER(19)").HasColumnName("ID_TALHAO");
            b.HasKey("Id");
            b.HasIndex("Codigo").IsUnique();
            b.HasIndex("IdTalhao");
            b.ToTable("SENSOR");
        });

        modelBuilder.Entity("AgroSat.Api.Models.LeituraSensor", b =>
        {
            b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("NUMBER(19)")
                .HasColumnName("ID_LEITURA").HasDefaultValueSql("SEQ_LEITURA.NEXTVAL");
            b.Property<long>("IdSensor").HasColumnType("NUMBER(19)").HasColumnName("ID_SENSOR");
            b.Property<decimal?>("UmidadeSolo").HasColumnType("NUMBER(5,2)").HasColumnName("UMIDADE_SOLO");
            b.Property<decimal?>("Temperatura").HasColumnType("NUMBER(5,2)").HasColumnName("TEMPERATURA");
            b.Property<decimal?>("UmidadeAr").HasColumnType("NUMBER(5,2)").HasColumnName("UMIDADE_AR");
            b.Property<decimal?>("Luminosidade").HasColumnType("NUMBER(7,2)").HasColumnName("LUMINOSIDADE");
            b.Property<DateTime?>("DataHora").HasColumnType("TIMESTAMP(7)").HasColumnName("DATA_HORA");
            b.HasKey("Id");
            b.HasIndex("IdSensor");
            b.ToTable("LEITURA_SENSOR");
        });

        modelBuilder.Entity("AgroSat.Api.Models.DadoSatelite", b =>
        {
            b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("NUMBER(19)")
                .HasColumnName("ID_DADO_SAT").HasDefaultValueSql("SEQ_DADO_SAT.NEXTVAL");
            b.Property<long>("IdTalhao").HasColumnType("NUMBER(19)").HasColumnName("ID_TALHAO");
            b.Property<decimal?>("Ndvi").HasColumnType("NUMBER(4,3)").HasColumnName("NDVI");
            b.Property<decimal?>("UmidadeEstimada").HasColumnType("NUMBER(5,2)").HasColumnName("UMIDADE_ESTIMADA");
            b.Property<decimal?>("IndiceChuvaMm").HasColumnType("NUMBER(6,2)").HasColumnName("INDICE_CHUVA_MM");
            b.Property<DateTime?>("DataReferencia").HasColumnType("TIMESTAMP(7)").HasColumnName("DATA_REFERENCIA");
            b.HasKey("Id");
            b.HasIndex("IdTalhao");
            b.ToTable("DADO_SATELITE");
        });

        modelBuilder.Entity("AgroSat.Api.Models.AlertaAgricola", b =>
        {
            b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("NUMBER(19)")
                .HasColumnName("ID_ALERTA").HasDefaultValueSql("SEQ_ALERTA.NEXTVAL");
            b.Property<long>("IdTalhao").HasColumnType("NUMBER(19)").HasColumnName("ID_TALHAO");
            b.Property<string>("Tipo").HasMaxLength(30).HasColumnType("NVARCHAR2(30)").HasColumnName("TIPO");
            b.Property<string>("Severidade").HasMaxLength(20).HasColumnType("NVARCHAR2(20)").HasColumnName("SEVERIDADE");
            b.Property<string>("Mensagem").HasMaxLength(255).HasColumnType("NVARCHAR2(255)").HasColumnName("MENSAGEM");
            b.Property<DateTime?>("DataHora").HasColumnType("TIMESTAMP(7)").HasColumnName("DATA_HORA");
            b.Property<string>("Resolvido").HasMaxLength(1).HasColumnType("NVARCHAR2(1)").HasColumnName("RESOLVIDO");
            b.HasKey("Id");
            b.HasIndex("IdTalhao");
            b.ToTable("ALERTA_AGRICOLA");
        });

        modelBuilder.Entity("AgroSat.Api.Models.Recomendacao", b =>
        {
            b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("NUMBER(19)")
                .HasColumnName("ID_RECOMENDACAO").HasDefaultValueSql("SEQ_RECOMENDACAO.NEXTVAL");
            b.Property<long>("IdTalhao").HasColumnType("NUMBER(19)").HasColumnName("ID_TALHAO");
            b.Property<long?>("IdAlerta").HasColumnType("NUMBER(19)").HasColumnName("ID_ALERTA");
            b.Property<string>("Tipo").HasMaxLength(40).HasColumnType("NVARCHAR2(40)").HasColumnName("TIPO");
            b.Property<string>("Texto").HasMaxLength(255).HasColumnType("NVARCHAR2(255)").HasColumnName("TEXTO");
            b.Property<DateTime?>("DataHora").HasColumnType("TIMESTAMP(7)").HasColumnName("DATA_HORA");
            b.HasKey("Id");
            b.HasIndex("IdTalhao");
            b.HasIndex("IdAlerta");
            b.ToTable("RECOMENDACAO");
        });

        modelBuilder.Entity("AgroSat.Api.Models.Irrigacao", b =>
        {
            b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("NUMBER(19)")
                .HasColumnName("ID_IRRIGACAO").HasDefaultValueSql("SEQ_IRRIGACAO.NEXTVAL");
            b.Property<long>("IdTalhao").HasColumnType("NUMBER(19)").HasColumnName("ID_TALHAO");
            b.Property<DateTime?>("Inicio").HasColumnType("TIMESTAMP(7)").HasColumnName("INICIO");
            b.Property<DateTime?>("Fim").HasColumnType("TIMESTAMP(7)").HasColumnName("FIM");
            b.Property<decimal?>("VolumeLitros").HasColumnType("NUMBER(10,2)").HasColumnName("VOLUME_LITROS");
            b.Property<string>("Modo").HasMaxLength(10).HasColumnType("NVARCHAR2(10)").HasColumnName("MODO");
            b.HasKey("Id");
            b.HasIndex("IdTalhao");
            b.ToTable("IRRIGACAO");
        });

        // -------- Relacionamentos --------
        modelBuilder.Entity("AgroSat.Api.Models.Propriedade", b =>
        {
            b.HasOne("AgroSat.Api.Models.Usuario", "Usuario").WithMany("Propriedades")
                .HasForeignKey("IdUsuario").OnDelete(DeleteBehavior.Restrict).IsRequired();
            b.Navigation("Usuario");
        });

        modelBuilder.Entity("AgroSat.Api.Models.Talhao", b =>
        {
            b.HasOne("AgroSat.Api.Models.Propriedade", "Propriedade").WithMany("Talhoes")
                .HasForeignKey("IdPropriedade").OnDelete(DeleteBehavior.Restrict).IsRequired();
            b.HasOne("AgroSat.Api.Models.Cultura", "Cultura").WithMany("Talhoes")
                .HasForeignKey("IdCultura").OnDelete(DeleteBehavior.SetNull);
            b.Navigation("Propriedade");
            b.Navigation("Cultura");
        });

        modelBuilder.Entity("AgroSat.Api.Models.Sensor", b =>
        {
            b.HasOne("AgroSat.Api.Models.Talhao", "Talhao").WithMany("Sensores")
                .HasForeignKey("IdTalhao").OnDelete(DeleteBehavior.Restrict).IsRequired();
            b.Navigation("Talhao");
        });

        modelBuilder.Entity("AgroSat.Api.Models.LeituraSensor", b =>
        {
            b.HasOne("AgroSat.Api.Models.Sensor", "Sensor").WithMany("Leituras")
                .HasForeignKey("IdSensor").OnDelete(DeleteBehavior.Restrict).IsRequired();
            b.Navigation("Sensor");
        });

        modelBuilder.Entity("AgroSat.Api.Models.DadoSatelite", b =>
        {
            b.HasOne("AgroSat.Api.Models.Talhao", "Talhao").WithMany("DadosSatelite")
                .HasForeignKey("IdTalhao").OnDelete(DeleteBehavior.Restrict).IsRequired();
            b.Navigation("Talhao");
        });

        modelBuilder.Entity("AgroSat.Api.Models.AlertaAgricola", b =>
        {
            b.HasOne("AgroSat.Api.Models.Talhao", "Talhao").WithMany("Alertas")
                .HasForeignKey("IdTalhao").OnDelete(DeleteBehavior.Restrict).IsRequired();
            b.Navigation("Talhao");
        });

        modelBuilder.Entity("AgroSat.Api.Models.Recomendacao", b =>
        {
            b.HasOne("AgroSat.Api.Models.Talhao", "Talhao").WithMany("Recomendacoes")
                .HasForeignKey("IdTalhao").OnDelete(DeleteBehavior.Restrict).IsRequired();
            b.HasOne("AgroSat.Api.Models.AlertaAgricola", "Alerta").WithMany("Recomendacoes")
                .HasForeignKey("IdAlerta").OnDelete(DeleteBehavior.SetNull);
            b.Navigation("Talhao");
            b.Navigation("Alerta");
        });

        modelBuilder.Entity("AgroSat.Api.Models.Irrigacao", b =>
        {
            b.HasOne("AgroSat.Api.Models.Talhao", "Talhao").WithMany("Irrigacoes")
                .HasForeignKey("IdTalhao").OnDelete(DeleteBehavior.Restrict).IsRequired();
            b.Navigation("Talhao");
        });

        // -------- Navegacoes inversas --------
        modelBuilder.Entity("AgroSat.Api.Models.Usuario", b => b.Navigation("Propriedades"));
        modelBuilder.Entity("AgroSat.Api.Models.Cultura", b => b.Navigation("Talhoes"));
        modelBuilder.Entity("AgroSat.Api.Models.Propriedade", b => b.Navigation("Talhoes"));
        modelBuilder.Entity("AgroSat.Api.Models.Talhao", b =>
        {
            b.Navigation("Sensores");
            b.Navigation("DadosSatelite");
            b.Navigation("Alertas");
            b.Navigation("Recomendacoes");
            b.Navigation("Irrigacoes");
        });
        modelBuilder.Entity("AgroSat.Api.Models.Sensor", b => b.Navigation("Leituras"));
        modelBuilder.Entity("AgroSat.Api.Models.AlertaAgricola", b => b.Navigation("Recomendacoes"));
#pragma warning restore 612, 618
    }
}
